# Generated by Django 4.2.11 on 2024-12-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(unique=True)),
                ('StaffUsername', models.CharField(max_length=20)),
                ('Staff', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Category', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('Authority', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant', models.CharField(max_length=50, null=True)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField(null=True)),
                ('FinishedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50, null=True)),
                ('Project', models.CharField(max_length=50, null=True)),
                ('StandardName', models.CharField(max_length=50, null=True)),
                ('StandardNumber', models.CharField(max_length=50, null=True)),
                ('ClauseNumber', models.CharField(max_length=50, null=True)),
                ('Equipment', models.CharField(max_length=50, null=True)),
                ('Manufacturer', models.CharField(max_length=50, null=True)),
                ('Photo', models.CharField(max_length=50, null=True)),
                ('Detail', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submitter', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('EquipmentName', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('Photo', models.CharField(max_length=100)),
                ('State', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('Paper', models.FileField(upload_to='Papers/')),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BroadCategory', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('Staff', models.CharField(max_length=50)),
                ('Equipment', models.CharField(max_length=200)),
                ('Procedure', models.CharField(max_length=50)),
                ('Sample', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50, null=True)),
                ('Project', models.CharField(max_length=50, null=True)),
                ('StandardName', models.CharField(max_length=50, null=True)),
                ('StandardNumber', models.CharField(max_length=50, null=True)),
                ('ClauseNumber', models.CharField(max_length=50, null=True)),
                ('Regulation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submitter', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('Staff', models.CharField(max_length=200)),
                ('EquipmentName', models.CharField(max_length=200)),
                ('Regulation', models.CharField(max_length=200)),
                ('Sample', models.CharField(max_length=200)),
                ('State', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sample', models.CharField(max_length=50, null=True)),
                ('Specification', models.CharField(max_length=50, null=True)),
                ('Manufacturer', models.CharField(max_length=50, null=True)),
                ('BatchNumber', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SamplePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submitter', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('Sample', models.CharField(max_length=50)),
                ('Specification', models.CharField(max_length=50)),
                ('Manufacturer', models.CharField(max_length=50)),
                ('BatchNumber', models.CharField(max_length=50)),
                ('RequiredQuantity', models.IntegerField()),
                ('ActualQuantity', models.IntegerField()),
                ('ApplicationTime', models.DateTimeField()),
                ('DeliveryTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BroadCategory', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('TraFinTime', models.DateTimeField()),
                ('TraCertification', models.CharField(max_length=100, unique=True)),
                ('ExamTime', models.DateTimeField()),
                ('TestFile', models.CharField(max_length=100, unique=True)),
                ('AuthCertification', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Project', models.CharField(max_length=50)),
                ('StandardName', models.CharField(max_length=50)),
                ('StandardNumber', models.CharField(max_length=50)),
                ('ClauseNumber', models.CharField(max_length=50)),
                ('Tutorial', models.FileField(upload_to='Tutorial/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Institution', models.CharField(max_length=20)),
                ('Identity', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('Identity', 'SupportStaff'), ('Identity', 'TestStaff'), ('Identity', 'Administer'), ('Identity', 'PotentialCustomer'), _connector='OR'), name='CheckUserIdentity'),
        ),
        migrations.AddField(
            model_name='tutorials',
            name='Tutorials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AddField(
            model_name='teststaff',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects1', to='Project.project'),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('Category', 'Project', 'StandardName', 'StandardNumber'), name='UniqueStandard'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('Sample', 'Specification', 'Manufacturer', 'BatchNumber'), name='UniqueSample'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(check=models.Q(('State', 'Pending'), ('State', 'Finished'), _connector='OR'), name='CheckReminderState'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects3', to='Project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Project.standard'),
        ),
        migrations.AddField(
            model_name='papers',
            name='Papers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
        migrations.AddConstraint(
            model_name='equippurchase',
            constraint=models.CheckConstraint(check=models.Q(('State', 'Pending'), ('State', 'Finished'), _connector='OR'), name='CheckEquipPurchaseState'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects2', to='Project.project'),
        ),
        migrations.AddField(
            model_name='comparison',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects4', to='Project.project'),
        ),
        migrations.AddConstraint(
            model_name='papers',
            constraint=models.CheckConstraint(check=models.Q(('Type', 'blank'), ('Type', 'submit'), ('Type', 'response'), _connector='OR'), name='CheckPaperType'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('Equipment', 'Manufacturer', 'Photo'), name='UniqueEquipment'),
        ),
    ]
