# Generated by Django 4.2.11 on 2024-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equippurchase',
            name='CheckEquipPurchaseState',
        ),
        migrations.RemoveConstraint(
            model_name='reminder',
            name='CheckReminderState',
        ),
        migrations.AddConstraint(
            model_name='equippurchase',
            constraint=models.CheckConstraint(check=models.Q(('State', 'Pending'), ('State', 'Finished'), _connector='OR'), name='CheckEquipPurchaseState'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(check=models.Q(('State', 'Pending'), ('State', 'Finished'), _connector='OR'), name='CheckReminderState'),
        ),
    ]
