# Generated by Django 4.2.11 on 2024-12-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorials',
            name='Tutorials',
        ),
        migrations.AddField(
            model_name='tutorials',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects5', to='Project.project'),
            preserve_default=False,
        ),
    ]
