# Generated by Django 4.2.11 on 2024-12-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_equippurchase_checkequippurchasestate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='standard',
            name='UniqueStandard',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='ClauseNumber',
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('Category', 'Project', 'StandardName', 'StandardNumber'), name='UniqueStandard'),
        ),
    ]
