# Generated by Django 4.2.11 on 2024-12-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_remove_standard_uniquestandard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Project.standard'),
        ),
    ]
