# Generated by Django 4.2.11 on 2024-12-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_project_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects4', to='Project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects2', to='Project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regulation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects3', to='Project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teststaff',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects1', to='Project.project'),
            preserve_default=False,
        ),
    ]
